### ISSUE TITLE
LME vs. BIC for model estimation

### ISSUE THREAD

**Issue by binwang87828** [translationalneuromodeling/tapas#80] opened 2020-02-04 12:40 UTC
Dear Dr. Mathys,

I hope you had a good move and good start. 

I have a question regarding the model estimation using LME and BIC. The toolbox provides both LME and BIC (also AIC) for the measure of model quality. When I compare two models (i.e., HGF and RW), the LME shows most of participants prefer the HGF model (more is better) as shown in figure below:
![Capture](https://user-images.githubusercontent.com/43343685/73745069-72f87f80-4752-11ea-948f-edfdeb524a12.JPG)

while BIC reveals all of participants prefer RW model (less is better) as shown in figure below:
![Capture2](https://user-images.githubusercontent.com/43343685/73745314-0631b500-4753-11ea-87f2-ed5a31fd3f91.JPG)

The result of BIC doesn't make sense, right? Did I misunderstand something about the BIC values that the toolbox gives? Any hint would be appreciated. 
Thank you very much for your time. 

Best,
Bin

**Comment by chmathys** [comment] 2020-05-20 09:03
Dear Bin,

Sorry for the slow response. Your question came just as I was moving to a new university in a new country and just before the virus struck.

I wouldn’t say the BIC results don’t make sense. They are what they are, but all model comparison methods have their limitations. In general, LME is a better measure than BIC because it is based on a more sophisticated concept of complexity, but also there you should keep in mind that its calculation is partly based on approximations.

In choosing a model, I recommend asking yourself three questions:

1) Does the model allow me to address my question of interest? (For example, if you want to know how your subjects deal with uncertainty about hidden states, it makes no sense to use a model that doesn’t contain such a quantity even if it performs better in the formal model comparison).

2) Does the prior predictive distribution make sense? (I.e., when sampling parameter values from the prior and simulating the implied belief trajectories and decisions, is the resulting distribution of trajectories and decisions plausible?)

3) Does the posterior predictive distribution make sense? (I.e., when simulating decisions with parameter values estimated from actual behaviour, can I reproduce the patterns I see in the actual behaviour [differences subject groups, conditions, etc.]?)

When the answer to all three is yes, your model is fine as far as I’m concerned.

Best wishes,

Christoph

**Closed** 2021-09-09 14:17 UTC
Labels: hgf
